# Generated by Django 3.2.5 on 2022-03-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220314_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.CharField(max_length=8192),
        ),
    ]
